###################################################
###################################################
###################################################
###################################################
description: "mage hand 2: state -> T[q]. assumes only rigid bodies for now. all poses are relative to the pose_state, so therefore we don't need to pass in pose_state. Reduce target pose to just position for a simpler learning problem for PoC. Pose is ALWAYS ordered wxyz, xyz, aka quat, pos, in order to be consistent with Drake"
# global controls
debug: false # 
single_thread: false
total_num_epochs: 2001
batches_per_epoch: 100
batch_size: 128
val_every: 20

### Global Control Panel ###
to_load:
  # - critic
  - actor
  # - res_actor
  - globals

# hack
resume: false

# should be the same as this file's name (sans .yaml)
run_tag: mage_hand

resume_tag: latest
output_dir: /media/dexnex_ssd/models/mage_hand

tasks_to_use:
  - all
  # - success
  # - failure

# which obs the obs_encoder (aka the policy) will use -- note: they don't actually have to exist in the dataset, but they do have to be produced by the sampler
obs_keys_to_use:
  # - yaw_pose_state # just for reference. This has been factored out to reduce input dimensionality
  - pose_pitch_roll # need to know the robot's current state
  - joint_state # need to know the robot's current state
  - haptics # need to know the robot's current state
  - rel_fk # need to know the robot's current state
  - rel_object_pos # need to know the object's current state
  - rel_object_target_pos # need to know the object's target state

# unused, but nice for reference
action_keys_to_use:
  - joint_action # need to know how to move the robot
  - rel_pos_action # need to know how to move the robot
  - rel_quat_action # need to know how to move the robot

# which obs the sarsa_sampler will load from the replay buffer -- also used in BatchLoader.get_static_nns
obs_keys_to_load:
  - pose_pitch_roll
  - joint_state
  - haptics
  - rel_fk
  - rel_object_pos
  - rel_object_target_pos

models_to_train:
  - actor
  # - res_actor
  # - critic

# irrelevant when using CriticBatchLoss
models_to_eval:
  - actor
  # - res_actor
  # - critic

# higher value means less frequent updates
step_freqs:
  actor: 1
  res_actor: 1
  critic: 1
  sac_actor: 1

use_bc_loss: true
action_relative_to_state: false
use_denoise: false # false for residual actor
### End Global Control Panel ###

num_inference_steps: 16 # for inference

# experiment with clamping on all object rel inputs to ensure no out of distribution inputs when doing inference
clamp: true # clamp actions (and diffusion noise)

# rollouts?
use_online_rollout: true
rollout_frequency: 500
rollout_warmup_nb_steps: 1499

###################################################
###################################################
###################################################
###################################################
# action_rel_indices: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16] # 0 is current idx, negative number is in the past, positive number is in the future
action_rel_indices: [1, 2, 3, 4, 5, 6, 7, 8]
obs_rel_indices: [0] # for now this is only allowed to be [0]
gradient_accumulate_every: 1 # may move this to ModelandEma later

# global_checkpointer:
#   _target_: diffusion_policy.common.checkpointer.GlobalCheckpointer


checkpoint:
  _target_: diffusion_policy.common.checkpointer.TopKCheckpointManager
  save_last_ckpt: true
  save_last_snapshot: false

  format_str: step={global_step:07d}.ckpt
  k: 50 # nb checkpoints to keep
  checkpoint_every: 50 # how often, in epochs
  mode: max
  monitor_key: epoch
  use_current_directory: false # use ${output_dir} as the base

  # required if resuming
  resume: ${resume}
  resume_tag: ${resume_tag}
  # output_dir: "/media/dexnex_ssd/models/${now:%Y.%m.%d}/${now:%H.%M.%S}"
  output_dir: ${output_dir}

# common data
shape_meta:  
  pose_pitch_roll:
    shape:
    - 2 # pitch, roll

  pose_state:
    shape:
    - 7 # root pose (7)

  joint_state:
    shape:
    - 22 # th (5), ff (4), mf (4), rf (4), lf (5)

  haptics:
    shape:
    - 5 # biotac (5)

  rel_fk:
    shape:
    - 15 # thtip (3), fftip (3), mftip (3), rftip (3), lftip (3)

  object_id:
    shape:
    - 1 # 1 id. agent needs some way to differentiate between types of objects

  # this is the object's position, relative to the robot's position
  rel_object_pos:
    shape:
      - 3 # xyz only

  rel_object_target_pose:
    shape:
      - 7 # wxyz, xyz. agent needs to know where the object is

  rel_object_target_pos:
    shape:
      - 3 # xyz only

  rel_object_target_quat:
    shape:
      - 4 # wxyz only

  joint_action:
    shape:
    - 22 # th (5), ff (4), mf (4), rf (4), lf (5)


  rel_pose_action:
    shape:
    - 7 # pose (7)

  rel_pos_action:
    shape:
    - 3 # pos (3)

  rel_quat_action:
    shape:
    - 4 # quat (4)

  action:
    shape:
    - 29 # joint_action (22) + rel_pose_action (7)


training:
  max_train_steps: null
  max_val_steps: null
  sample_every: 2
  seed: 42
  tqdm_interval_sec: 1.0


logging:
  _target_: diffusion_policy.common.logging.Logging
  use_wandb: true

  wandb_cfg:
    group: null
    id: null
    mode: online # don't change this
    name: 2025.diffusion_ql
    project: dexnex_diffusion
    resume: true # wandb automatic resume
    tags:
    - diffusion_ql
    - cotrain
    - default

common_obs_encoder:
  _target_: diffusion_policy.model.obs_encoder.ObsEncoderMaker

  obs_keys_to_use: ${obs_keys_to_use}

  rgbs: {} # dummy
  ch: 0 # dummy
  cw: 0 # dummy

  # this is still needed because some obs are images and others are lowdims. Can get the shape from shape meta though
  lowdims:
    - pose_pitch_roll
    - joint_state
    - haptics
    - rel_fk
    - rel_object_pos
    - rel_object_target_pos



common_indices:
  _target_: diffusion_policy.common.sarsa_sampler.Indices
  rb_id: default
  rb_episode_start_idx: 0
  rb_episode_end: 0
  training_episode_start: 0
  training_episode_end: 0
  pad_before: 0
  pad_after: 0
  debug: ${debug}


data_directory: /media/dexnex_ssd/data/mage_hand/

# NODE -- replay buffer loader entry point
replay_buffer_loader:
  _target_: diffusion_policy.common.replay_buffer_loader.ReplayBufferLoader

  # NOTE -- the keys in these zarr datasets are ["img", "img2", "state", "action", "reward"]
  rb_paths:
    all: ${data_directory}mage_hand_test.zarr

  modes:
    all: r

# to be used for norming / unnorming without loading onto gpu (mostly for inference / rollouts)
default_batch_loader:
  _target_: diffusion_policy.dataset.batch_loader.MageHandBatchLoader
  rb_id: "all" # forces a load
  train_or_val: eval # unnecessary during inference
  use_dataloader: false # must be false during inference
  strict: false # must be false for inference

# NODE -- training entry point
session_trainer:
  _target_: diffusion_policy.trainers.session_trainer.SessionTrainer
  nb_epochs: ${total_num_epochs} # testing
  
  # children
  epoch_trainer:
    _target_: diffusion_policy.trainers.epoch_trainer.EpochTrainer
    nb_batches: ${batches_per_epoch}

    # children
    step_trainer: 
      _target_: diffusion_policy.trainers.step_trainer.StepTrainer
      grad_norm: 1.0
    
      # weighted batch loss dict
      w_batch_losses:
        all: ${common_wbatch_loss}

    # alias: rollout:
    rollouts:
      _target_: projects.mage_hand.mage_hand_rollout.MageHandRollout
      freq: ${rollout_frequency} # in steps
      warmup_nb_steps: ${rollout_warmup_nb_steps}
      rb_id: all
      num_rollouts_per_trigger: 1
      use_online_rollout: ${use_online_rollout}
      rollout_num_actions: 8
      task_id: 0 # refer to tasks.md / task catalog
      use_critic_preferred_actions: false
      use_critic_preferred_actions_early_exit: false
      critic_preferred_actions_nb: 2
      only_save_successful_episodes: false
      save_rollouts: false
      use_energy_limited_actions: false


      evaluator:
        _target_: projects.mage_hand.mage_hand_evaluator.MageHandInference

        policy: null
        debug: ${debug}
        analytics: false
        task_id: ${..task_id}

  epoch_evaluator:
    _target_: diffusion_policy.trainers.epoch_trainer.EpochValidator
    nb_batches: 4
    val_every: ${val_every}

    # weighted batch loss dict
    w_batch_losses:
      all: ${common_wbatch_loss}



common_wbatch_loss:
  _target_: diffusion_policy.losses.batch_loss.WeightedBatchLoss
  weight: 1.0

  # children
  batch_loss:
    _target_: diffusion_policy.losses.batch_loss.BatchLoss
    use_bc_loss: ${use_bc_loss}
    freqs: ${step_freqs}
    eta: 1.0

    # children
    # for normalizing
    batch_loader:
      _target_: diffusion_policy.dataset.batch_loader.MageHandBatchLoader
      rb_id: default # forces a load
      train_or_val: train

dataloaders:
  _target_: diffusion_policy.dataset.train_and_val.DataLoaders

  d: 
    all: ${common_dataset}

common_dataset:
  _target_: diffusion_policy.dataset.train_and_val.TrainAndVal
  seed: 42
  val_ratio: 0.02
  max_train_episodes: null
  use_weighted_dataloader: false

  options:
    common:
      batch_size: ${batch_size}
      timeout: 0 # 0 means no timeout
    train:
      num_workers: 12
      persistent_workers: true
      pin_memory: true
      shuffle: true # can't use with use_weighted_dataloader
    val:
      num_workers: 0
      persistent_workers: false
      pin_memory: false
      shuffle: true # can't use with use_weighted_dataloader

  # child
  sampler:
    _target_: diffusion_policy.samplers.mage_hand_sampler.MageHandDatasetSampler
    rb_id: default

    ep_sampler_class_str: diffusion_policy.samplers.mage_hand_sampler.MageHandEpisodeSampler

    # child

# models node
models:
  _target_: diffusion_policy.model.models.Models

  models:
    actor:
      _target_: diffusion_policy.model.model.ModelEmaOptim

      # # checkpointer
      # checkpointer: ${common_checkpoint}

      model:
        _target_: diffusion_policy.model.model.Model
        model:
          _target_: diffusion_policy.model.diffusion_model.DiffusionModel
          action_shape: ${shape_meta.action.shape}
          noise_scheduler: ${common_noise_scheduler}
          obs_encoder_maker: ${common_obs_encoder}
          eval_fixed_crop: true
          obs_as_global_cond: true
          obs_encoder_group_norm: true
          n_obs_steps: 1 # how many indices from the end of ${obs_rel_indices} will the diffusion model use
          down_dims: # must be divisible by nb_groups (8)
            - 128
            - 256
            - 512
          diffusion_step_embed_dim: 32

          action_relative_to_state: ${action_relative_to_state}
          use_tree: false
          use_simple_model: false

      ema:
        _target_: diffusion_policy.model.model.Ema
        use_ema: true
        ema_cfg:
          inv_gamma: 1.0
          max_value: 0.9999
          min_value: 0.0
          power: 0.75
          update_after_step: 0

      optim:
        _target_: diffusion_policy.model.model.Optim

        # https://huggingface.co/docs/transformers/en/main_classes/optimizer_schedules#transformers.get_cosine_schedule_with_warmup
        lr_scheduler: cosine
        lr_warmup_steps: 500
        gradient_accumulate_every: 1
        optimizer_target: torch.optim.AdamW
        optimizer_cfg:
          betas:
            - 0.95
            - 0.999
          eps: 1.0e-08
          lr: 5e-4 # 1e-4
          weight_decay: 1.0e-06


common_noise_scheduler:
  _target_: diffusers.schedulers.scheduling_ddpm.DDPMScheduler
  beta_end: 0.02
  beta_schedule: squaredcos_cap_v2
  beta_start: 0.0001
  clip_sample: true # apparently you want this true when prediction_type is sample
  num_train_timesteps: 100
  prediction_type: epsilon # epsilon or sample
     
device: cuda:0

override:
  session_trainer:
    epoch_trainer:
      step_trainer: 
        w_batch_losses:
          all:
            weight: 1.0
            batch_loss: 
              batch_loader:
                rb_id: all
              use_bc_loss: ${use_bc_loss}
    epoch_evaluator:
      w_batch_losses:
        all:
          weight: 1.0
          batch_loss: 
            batch_loader:
              rb_id: all
              train_or_val: val
            use_bc_loss: ${use_bc_loss}

  dataloaders:
    d:
      all:
        sampler:
          rb_id: all

  models:
    models:
      actor:
        model:
          model:
            noise_scheduler:
              variance_type: fixed_small # ah, I need this here because it only exists in the DDPM scheduler, so it's not common to DDIM & DDPM